spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restful_api
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
logging:
  level:
    org.springframework.web: DEBUG
